### ISSUE TITLE
JIT-friendly mode

### ISSUE THREAD

**Issue by msridhar** [Samsung/jalangi2#10]
For experiments regarding performance overhead, it would be good to have a mode in which `esnstrument.js` does not create any code constructs known to stop V8 from applying its JIT.  As of now, the relevant constructs are:
1. try/finally blocks enclosing method bodies
2. referencing and escaping the `arguments` array
The JIT-friendly mode need not be suitable for writing analyses; it would just be used to be able to measure the overhead of the constructs across an array of runtimes.

**Comment by ksen007** [comment]
done.
