### ISSUE TITLE
Arrow function instrument error

### ISSUE THREAD

**Issue by liz425** [Samsung/jalangi2#114]
It seems that Jalangi2 currently does not support arrow function definition under Node v4.4.5.
I tried to upgrade Node to v6.9.1, then the example test "python script/test.analysis.py" failed on the 'const x = 3' test.
I'm not sure if this is caused by unsupporting of ES6. Does anyone encounter the same problem?
e.g. In line 118:
![image](https://cloud.githubusercontent.com/assets/6878804/20071681/04c1a918-a4eb-11e6-8d3e-6d5f54f362f2.png)
![image](https://cloud.githubusercontent.com/assets/6878804/20075142/ac13f11e-a4f8-11e6-9f24-6af2c09d25b3.png)

**Comment by msridhar** [comment]
ES6 in general is not supported at this time.  We also do not yet support Node 6.x.  The latter will likely happen before the former.  In the meantime, can you translate the code to ES5 (e.g., using babel) and then instrument under Node 4.x?

**Comment by liz425** [comment]
Thank you for your suggestion. I've tried to translate the code using Babel but didn't get any nice result yet. 
I'm quite new to JS instrument and have some doubts about it. Actually, I'm trying to instrument JS code of React Native framework, it may take hours to transform or instrument all those numerous files in node_modules.
So, can I use Jalangi2 to instrument part of the JS project rather than all JS files? Does Jalangi2 work where my JS code never terminate?

**Comment by msridhar** [comment]
You can definitely use Jalangi2 to only instrument part of a project.  But, your analysis may need to be aware of the fact that some code will be uninstrumented.

Yes, Jalangi 2 works even if the JS code does not terminate.

**Comment by msridhar** [comment]
I opened #115 on Node v6 support; closing this issue.
