### ISSUE TITLE
Record replay in jalangi 2 ?

### ISSUE THREAD

**Issue by ganarajpr** [Samsung/jalangi2#13]
I am not clear on whether record replay is not possible with jalangi2 because of some architectural changes / choices or is it that record replay engine has not been ported to jalangi2 (and hence it is possible if someone actually does the work )?

The reason I ask is , i am interested in the record replay part of jalangi - but I want to know which of the two forks to go forward with ? If its still possible with jalangi 2 I would be happy to put in the effort to port the record replay engine to jalangi 2 ?

**Comment by msridhar** [comment]
So the reasons we did not implement record/replay with the core of Jalangi2 were (1) it is very difficult to handle all the corner cases when replaying browser code on node.js and (2) it can hurt performance even for analyses that do not need record/replay.  As an alternative, [MemInsight](https://github.com/Samsung/meminsight) generates its own custom trace format, which it uses to perform an offline analysis without doing a full record replay.  I think this is the best technique to use going forward.  If you really want built-in record/replay, use the original Jalangi.

**Comment by ganarajpr** [comment]
So are you suggesting that its better to go with MemInsight as opposed to
jalangi ?  Is there some more information ( available anywhere ? ) on
MemInsight ( papers etc ? )  ? Or perhaps, any oter alternate such
javascript based record replay facilitates available ?

On Sat, Jan 31, 2015 at 1:45 PM, Manu Sridharan <notifications@github.com>
wrote:

> So the reasons we did not implement record/replay with the core of
> Jalangi2 were (1) it is very difficult to handle all the corner cases when
> replaying browser code on node.js and (2) it can hurt performance even for
> analyses that do not need record/replay. As an alternative, MemInsight
> <https://github.com/Samsung/meminsight> generates its own custom trace
> format, which it uses to perform an offline analysis without doing a full
> record replay. I think this is the best technique to use going forward. If
> you really want built-in record/replay, use the original Jalangi.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Samsung/jalangi2/issues/13#issuecomment-72318262>.
>



-- 
Regards,
Ganaraj P R

**Comment by msridhar** [comment]
MemInsight does not do general record/replay.  My point was that if you
want record / replay for a specific reason / client, I suggest implementing
a custom tracer for that client.  If you want general record/replay, use
the original Jalangi.  We are happy to accept patches for Jalangi if you
have fixes for issues there.
