### ISSUE TITLE
Exception check is wrong for `throw undefined`

### ISSUE THREAD

**Issue by esbena** [Samsung/jalangi2#2]
The two checks  in /src/js/runtime/analysis.js that check if an exception has been thrown are wrong.

The checks are implemented as 
```javascript
if (exceptionVal !== undefined) {...}
``` 

But this is wrong in the presence of `throw undefined`.

Example code to showcase wrongness:

Consider the empty analysis (../empty-analysis.js):
```javascript
(function (sandbox) {
    function MyAnalysis () {
    }
    sandbox.analysis = new MyAnalysis();
})(J$);
```
Consider the program:
../throw-undefined.js
```javascript
throw undefined;
```

Consider the shell session, which shows no errors:
```bash
$ node src/js/commands/esnstrument_cli.js ../throw-undefined.js && node src/js/commands/direct.js --analysis ../empty-analysis.js ../throw-undefined_jalangi_.js
$
```
But it should, because running `../throw-undefined.js` without jalangi, produces an error:
```bash
$ node ../throw-undefined.js

../throw-undefined.js:1
(function (exports, require, module, __filename, __dirname) { throw undefined;
                                                                    ^
undefined
```

**Comment by ksen007** [comment]
fixed
