### ISSUE TITLE
Wrong event order for getField on Firefox and Chrome

### ISSUE THREAD

**Issue by JacksonGL** [Samsung/jalangi2#42]
For the expression ```a.b(c)```, node.js engine will evaluate the sub-expressions in the following order: 
 * ```a``` 
 * ```c``` 
 * ```a.b```

However, in Chrome and Firefox, those sub-expressions are evaluated in a different order:
 * ```a```
 * ```a.b```
 * ```c```

**Problem**: for expression ```a.b(c)```, the instrumented code always emits ```getField a.b``` event after ```read c``` event.

Consider the following example code:

```javascript
var a = {
	get b() {
		console.log('getting b');
		return function (){};
	}
};

var d = {
	get e() {
		console.log('getting e');
		return function (){};
	}
};

console.log('--------------');
a.b(d.e);
console.log('--------------');
(1, a.b)(d.e)
```

Running the following example program in Chrome and Firefox produces the following result:
```
--------------
getting b
getting e
--------------
getting b
getting e
```

Running the instrumented example code on Chrome and Firefox produces a different result:
```
--------------
getting e
getting b
--------------
getting b
getting e
```
Therefore, the instrumentation process changes the semantics of the example code on Firefox and Chrome.

**Comment by msridhar** [comment]
@JacksonGL which node.js version are you referring to?  Does this still happen on node v0.12?

**Comment by JacksonGL** [comment]
Just updated to v0.12 (I was using node v0.10).  Now the output of the example program on node.js is consistent with those on Chrome and Firefox. So this problem also appears on node.js now.

**Comment by msridhar** [comment]
Ok.  Maybe we can just document this issue somewhere as a problem with node
0.10?  I don't think we need to go through much trouble to create a fix for
0.10 now that 0.12 is stable.

**Comment by JacksonGL** [comment]
The currently implementation of Jalangi2's event order is consistent with node 0.10. So it is not a bug for node 0.10. It is a bug for node 0.12, Firefox and Chrome.

**Comment by msridhar** [comment]
OK, Jalangi should be consistent with chrome and Firefox I think.
