### ISSUE TITLE
endExpression & sequence-expressions

### ISSUE THREAD

**Issue by esbena** [Samsung/jalangi2#5]
`J$.X1` is missing inside sequence-expressions, as the non-last
expressions are "end of expression" by themselves.

I suggest pushing J$.X1 onto all members of a sequence-expression.

Consider the two examples:

1)
```javascript
('a', 'b')
```
Is instrumented to:
```
J$.X1((J$.T(9, 'a', 21, false), J$.T(17, 'b', 21, false)));
```
But it should be:
```
(J$.X1(J$.T(9, 'a', 21, false), J$.X1(J$.T(17, 'b', 21, false)));
```

2)
```javascript
for('a', 'b';;);
```
Is instrumented to:
```
for (J$.X1((J$.T(25, 'a', 21, false), J$.T(33, 'b', 21, false)));;);
```
But it should be:
```
for ((J$.X1(J$.T(25, 'a', 21, false), J$.X1(J$.T(33, 'b', 21, false))));;);
```

(NB: AST-wise, the `node.type` of the sequence expression is: "SequenceExpression")

**Comment by ksen007** [comment]
fixed
