### ISSUE TITLE
Missing ReferenceError on undeclared variable references?

### ISSUE THREAD

**Issue by esbena** [Samsung/jalangi2#51]
Jalangi squelches the ReferenceError that would occur on a references to an undeclared variable through its use of `J$.I`.

This breaks feature-detection with try-catch blocks as seen below: 

```javascript
try {
    document; // <-- supposed to throw in non-browser environments
} catch (e) {
    standalone = true;
} 
```

Suggestion: the jalangi-instrumentation-pattern with `J$.I(...)` for undeclared variables should be disabled by default.
Thoughts?

---

##### Small example that showcases the discrepancy between a jalangi-runtime and a node-runtime:

test.js:
```javascript
DOES_NOT_EXIST;
```
test_jalangi_.js
```javascript
...
J$.X1(17, J$.I(typeof DOES_NOT_EXIST === 'undefined' ? DOES_NOT_EXIST = J$.R(9, 'DOES_NOT_EXIST', undefined, true, true) : DOES_NOT_EXIST = J$.R(9, 'DOES_NOT_EXIST', DOES_NOT_EXIST, true, true)));
...
```

```
$ node src/js/commands/jalangi.js test.js
$ node test.js
...
(function (exports, require, module, __filename, __dirname) { DOES_NOT_EXIST;
                                                              ^
ReferenceError: DOES_NOT_EXIST is not defined
...
```

**Comment by msridhar** [comment]
The discussion on SRA-SiliconValley/jalangi#19 is probably relevant.  I'd like to see a fix to this issue as well.  We should be able to do something simpler now that we don't need to support record-replay.  I am personally still ok with just getting rid of the `J$.I` callback in general and just doing:
```javascript
DOES_NOT_EXIST = J$.R(9, 'DOES_NOT_EXIST', DOES_NOT_EXIST, true, true)));
```
The negative effect is we lose the `readPre()` callback for undeclared variables, but to me that is not compelling given that we are currently breaking semantics.

**Comment by ksen007** [comment]
The fix was a bit involved because typeof DOES_NOT_EXIST won't throw an exception.
