### ISSUE TITLE
Confusing handling of global variables

### ISSUE THREAD

**Issue by johanneskloos** [Samsung/jalangi2#56]
The isGlobal and isScriptLocal parameters to the read and write callbacks have confusing and, in my opinion, inconsistent values when handling global variables.

Consider a simple analysis that just prints out the name of the variable and both flags on read and write (code below). Run it on the following piece of code:

```javascript
var x;
x=1;
x;
z = 1;
z;
console=console;
console;
```

What I would expect: The isGlobal and isScriptLocal variables should be the same in reads and writes to the same variable. Moreover, z would have either have isGlobal set and isScriptLocal unset, or vice-versa, and console would have isGlobal set and isScriptLocal unset.

What I get:
> Writing to x (script-local)
> Reading from x (script-local)
> Writing to z (local)
> Reading from z (global and script-local?!)
> Reading from console (global and script-local?!)
> Writing to console (local)
> Reading from console (global and script-local?!)

PS: Here is the analysis used:
```javascript
// JALANGI DO NOT INSTRUMENT
(function (sandbox) {
    function MyAnalysis () {
	function writeFlags(isGlobal, isScriptLocal) {
	    if (isGlobal && isScriptLocal) { return "global and script-local?!" }
	    else if (isGlobal) { return "global" }
	    else if (isScriptLocal) { return "script-local" }
	    else { return "local" }
	}
        this.read = function(iid, name, val, isGlobal, isScriptLocal){
	    console.log("Reading from " + name + " (" + writeFlags(isGlobal, isScriptLocal) + ")")
	};

        this.write = function(iid, name, val, lhs, isGlobal, isScriptLocal) {
	    console.log("Writing to " + name + " (" + writeFlags(isGlobal, isScriptLocal) + ")")
	};
    }
    sandbox.analysis = new MyAnalysis();
})(J$);
```

**Comment by ksen007** [comment]
let me take a look.

**Comment by johanneskloos** [comment]
JFTR: This was run under node v0.12.4 with jalangi2 as of commit 99d6f1aac9846c48d23d7843d6846d9a187e2faa (dated Jun 5).

**Comment by johanneskloos** [comment]
Retried with current git version of jalangi2. The results are still unexpected:Writing to x (script-local)
Reading from x (script-local)
Writing to z (global)
Reading from z (global and script-local?!)
Reading from console (global and script-local?!)
Writing to console (global)
Reading from console (global and script-local?!)

Note that the information between reads and writes differs.

**Comment by ksen007** [comment]
fixed
