### ISSUE TITLE
Documentation: isGlobal and eval interact in unexpected ways

### ISSUE THREAD

**Issue by johanneskloos** [Samsung/jalangi2#64]
The behavior of the isGlobal flag in the read and write callbacks interacts with evals in an unexpected way. Consider the following example:

```Javascript
var x = "magic";
console.log(x);
eval("console.log(x)");
```

Then reading `x` the first time will invoke the `read` callback with isGlobal=false and isScriptLocal=true (which is entirely expected, from the documentation), while the read in the eval will invoke the callback with isGlobal=true and isScriptLocal=true.

According to the documentation, isGlobal is "True if the variable is not declared using var", but in fact, isGlobal is "True if the variable is not declared using var in the current script".

Minimal analysis to reproduce:
```Javascript
(function (sandbox) {
    function MyAnalysis (global) {
        this.read = function(iid, name, val, isGlobal, isScriptLocal){
	    console.log("Reading " + name + ", isGlobal=" + isGlobal)
	};

        this.scriptEnter = function(iid, instrumentedFileName, originalFileName){
	    console.log("Entering script")
	};

        this.scriptExit = function(iid, wrappedExceptionVal){
	    console.log("Exiting script")
	};
    }
    sandbox.analysis = new MyAnalysis(this);
})(J$);
```

This yields:
```
Entering script
Reading console, isGlobal=true
Reading x, isGlobal=false
magic
Entering script
Reading console, isGlobal=true
Reading x, isGlobal=true
magic
Exiting script
Reading console, isGlobal=true
Reading x, isGlobal=false
magic
Exiting script
```

**Comment by ksen007** [comment]
The deviation from documentation happens because the flags are set during instrumentation.  To characterize the flags correctly within eval, we need runtime information which will have some overhead.  I am not sure if we want to do this.  Maybe we can fix the documentation.

**Comment by johanneskloos** [comment]
A documentation fix would be sufficient, I think. You can always compute the flags yourself in the analysis.

**Comment by johanneskloos** [comment]
The above merge closes this bug.
