### ISSUE TITLE
Content-type checking in proxy.py is too restrictive

### ISSUE THREAD

**Issue by Matthalp** [Samsung/jalangi2#70]
The following code in: https://github.com/Samsung/jalangi2/blob/master/scripts/proxy.py#L43
misses several files for instrumentation:

1. `Content-Type` is case insensitive (i.e can also be `content-type` or `CoNtEnT-tYpE`):
    http://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

```
def response(context, flow):
	flow.response.decode()
	if 'Content-Type' in flow.response.headers:
		if flow.response.headers['Content-Type'][0].find('javascript') != -1:
			flow.response.content = processFile(flow.response.content, "js")
		if flow.response.headers['Content-Type'][0].find('html') != -1:
			flow.response.content = processFile(flow.response.content, "html")
```

You could try this:

```
def content_type(headers):
    for key in headers.keys():
        if key.lower() == "content-type":
            return headers[key].lower()
    return None

def response(context, flow):
    flow.response.decode()
    if 'javascript' in content_type(flow.response.headers):
        flow.response.content = processFile(flow.response.content, "js")
    elif 'html' in content_type(flow.response.headers):
        flow.response.content = processFile(flow.response.content, "html")
```

2. You might want to looking at the extension of the path (i.e. filename: `flow.request.path.split('/')[-1]` or ext `flow.request.path.split('.')[-1]` -- with appropriate string sanitization)

**Comment by ksen007** [comment]
mitmproxy is kind of broken.  I will be happy to merge a pull request which fixes all mitmproxy related issues.
