### ISSUE TITLE
iidToLocation of write operations on update expressions (i++) not being set

### ISSUE THREAD

**Issue by omrsin** [Samsung/jalangi2#72]
When running an analysis on a portion of code that contains update expressions (such as i++) I found out that jalangi is not able to return the location of this instruction in the original code. 

The iidToLocation function returns the same iid most likely because in the iidToLocation.js the value of arr is falsy

```javascript
arr = ret[iid];
if (arr) {
    if (sandbox.Results) {
        return "<a href=\"javascript:iidToDisplayCodeLocation('"+gid+"');\">(" + fname + ":" + arr[0] + ":" + arr[1] + ":" + arr[2] + ":" + arr[3] + ")</a>";
    } else {
        return "(" + fname + ":" + arr[0] + ":" + arr[1] + ":" + arr[2] + ":" + arr[3] + ")";
    }
} else {
    return "(" + fname + ":iid" + iid + ")";
}
```

**Comment by esbena** [comment]
There is a TODO in analysis.js about that synthetic iid not being present in the source map.

https://github.com/Samsung/jalangi2/blob/master/src/js/runtime/analysis.js#L514

I my projects, I have worked around the issue by incrementing the iid by two and calling iidToLocation again.

**Comment by msridhar** [comment]
@esbena what exactly is your workaround?  Is that a patch to jalangi or a change in your analysis?

**Comment by esbena** [comment]
My workaround is applied after Jalangi has finished running, using completely different data structures.

But during Jalangi-runtime my fix would look like this:


```javascript
function iidToLocation_FIXED(iid){
  if(sandbox.iidToLocation(iid) === iid /* what @omrsin reports as symptom */){
     iid = iid - 2; // Undo use of unmapped iid: https://github.com/Samsung/jalangi2/blob/master/src/js/runtime/analysis.js#L514
  }
  return sandbox.iidToLocation(iid);
}
// (needs adjustment for sid/gid)
```

**Comment by esbena** [comment]
IMO The proper fix is to have the iid in the sourcemap from the beginning.

**Comment by ksen007** [comment]
fixed
