### ISSUE TITLE
Declare hook is not firing when same variable is declared again.

### ISSUE THREAD

**Issue by anasanjaria** [Samsung/jalangi2#75]
Consider following code :

```
var answer = 42;
var answer = 12;
```

Here the variable ```answer``` is declared twice so as per my knowledge declare hook should also be called twice but in actual it is not. Can you please let me know if this is bug ?

**Comment by ksen007** [comment]
Jalangi does not fire declare based on the syntactic location of a var location.  It is fired at the beginning of a function/method block irrespective of where the variable is declared in the function body.  The philosophy behind Jalangi's dynamic analysis is that we provide a minimal set of callbacks and we try to be independent of syntactic structures.
