### ISSUE TITLE
Proxy script not running in mitmproxy 0.14

### ISSUE THREAD

**Issue by martinbilles** [Samsung/jalangi2#77]
The last working version of mitmproxy to run Jalangi's test script on seems to be mitmproxy 0.13

For mitmproxy 0.15, there is a syntax error, see mitmproxy/mitmproxy#903

For mitmproxy 0.14, mitmdump will start without error, but the analysis will not run, and no Jalangi overlay will be visible on the browser window.

This is the same configuration (Ubuntu 14.04, Firefox 44), only the version of mitmproxy is different:

```
mitmdump -q --anticache -s "../scripts/proxy.py --analysis ../src/js/sample_analyses/ChainedAnalyses.js --analysis ../src/js/runtime/analysisCallbackTemplate.js"
```

Output for mitmproxy 0.13 when visiting example.com in Firefox:
```
Jalangi home is /home/martin/git/jalangi2
Current working directory is /home/martin/git/jalangi2/tmp
--analysis /home/martin/git/jalangi2/src/js/sample_analyses/ChainedAnalyses.js --analysis /home/martin/git/jalangi2/src/js/runtime/analysisCallbackTemplate.js
Storing and instrumenting 09b9c392dc1f6e914cea287cb6be34b0.html
node /home/martin/git/jalangi2/src/js/commands/esnstrument_cli.js --inlineIID --inlineSource --analysis /home/martin/git/jalangi2/src/js/sample_analyses/ChainedAnalyses.js --analysis /home/martin/git/jalangi2/src/js/runtime/analysisCallbackTemplate.js 09b9c392dc1f6e914cea287cb6be34b0.html
```

For mitmproxy 0.14, the output is:
```
Jalangi home is /home/martin/git/jalangi2
Current working directory is /home/martin/git/jalangi2/tmp
--analysis /home/martin/git/jalangi2/src/js/sample_analyses/ChainedAnalyses.js --analysis /home/martin/git/jalangi2/src/js/runtime/analysisCallbackTemplate.js
```

No instrumentation is performed for mitmproxy 0.14.

mitmproxy 0.13: working
mitmproxy 0.14: launching but no instrumentation
mitmproxy 0.15: syntax error mitmproxy/mitmproxy#903

(You can test different mitmproxy versions with `pip install mitmproxy==version`, e.g. `pip install mitmproxy=0.14`, and review your currently installed version with `pip show mitmproxy`.)

**Comment by martinbilles** [comment]
I retested this considering #78, and even when creating a new temporary folder and running mitmproxy-0.14 in that one produces no instrumentation.

**Comment by ksen007** [comment]
I will be happy to merge a pull request that fixes this issue.
