### ISSUE TITLE
source locations are slightly off when highlighting with istanbul

### ISSUE THREAD

**Issue by msridhar** [Samsung/jalangi2#83]
With [this version](https://github.com/Samsung/jalangi2/files/119662/esprima.org.js.zip) of esprima, we get the following `statementMap` entry:

```
			"5583": {
				"start": {
					"line": 3598,
					"column": 14
				},
				"end": {
					"line": 3598,
					"column": 31
				}
			},
```
Here is how it gets highlighted in istanbul:
![screen shot 2016-02-05 at 10 24 19 am](https://cloud.githubusercontent.com/assets/193105/12855263/50b6e0bc-cbf3-11e5-95fa-3f83b7e76db3.png)

There are two problems:
* It looks like istanbul assumes a initial column number of 0 on each line instead of 1.  So, it'd be good if the start column were 13 instead of 14.
* Even if the initial column number were 1, the end column is still wrong above; it should be 30, not 31.  (With 0 as the initial column number, we want 29.)  So this looks like a separate issue with end columns.

**Comment by ksen007** [comment]
fixed
