### ISSUE TITLE
[Feature Request] Transparent analysis?

### ISSUE THREAD

**Issue by zb3** [Samsung/jalangi2#98]
Maybe I am asking a stupid question or this project was not intended to do what I was trying to..
But currently the analysed script knows if it's analysed, therefore I am unable to analyse it, because it simply won't run if it detects something strange in the environment, which is why I wanted to analyse it in first place...

For instance, consider this:
```
var encrypted_code; //encrypted with some kind of environment fingerprint

eval(decrypt(encrypted_code), typeof J$ + (function s(){return s.toString()})() + AudioStreamTrack);
```

This is of course very simple to analyse, however malware is generally way more sophisticated and employs many other detection features (including timing analysis).

So is this project not suitable for malware analysis by design? If so, are there any other projects that are suitable for that? Then forgive me, I couldn't find any..

Since jalangi analyses can intercept everything, making the analysis transparent is indeed possible via a special analysis file, however is something like this planned? I cannot work on this due to lack of time.

**Comment by msridhar** [comment]
We don't have a strong desire to do the work required to make Jalangi transparent.  One issue is that Jalangi affects call stacks for exceptions.  So, any JavaScript program could create a call stack and inspect it, and see if Jalangi instrumentation has been applied.  I don't see an easy way to work around this problem.

I'm not immediately aware of other instrumentation-based approaches that are transparent to the underlying code.  Sorry we can't be more helpful.
